name: camera_view_mask
description: Add your mask to camera view.
publish_to: "none"
version: 0.1.1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.2.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  camera: ^0.11.0+1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  dart_code_metrics: ^5.7.6
